"""added aswered state to question

Revision ID: 30c21e30605e
Revises: 33585bb5d9a4
Create Date: 2023-11-04 16:20:23.314212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c21e30605e'
down_revision = '33585bb5d9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multiple_choice_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multiple_choice_question', schema=None) as batch_op:
        batch_op.drop_column('answered')

    # ### end Alembic commands ###
