"""Added MultipleChoice Question

Revision ID: 7f95d54fb4c7
Revises: 2122c97b230c
Create Date: 2023-08-19 16:09:02.984183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f95d54fb4c7'
down_revision = '2122c97b230c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_question',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answers', sa.Integer(), nullable=True),
    sa.Column('creation_timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('room_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_players', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('question_index')

    op.drop_table('room_question')
    # ### end Alembic commands ###
