"""Updated answers

Revision ID: 93ee89b998e9
Revises: 99e8d4cee9b8
Create Date: 2023-08-20 14:29:04.783194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ee89b998e9'
down_revision = '99e8d4cee9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.create_table('multiple_choice_question',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('creation_timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.drop_table('room_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_question',
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('index', sa.INTEGER(), nullable=True),
    sa.Column('question', sa.TEXT(), nullable=True),
    sa.Column('answer', sa.TEXT(), nullable=True),
    sa.Column('creation_timestamp', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.drop_table('multiple_choice_question')
    op.drop_table('answer')
    # ### end Alembic commands ###
