"""Redid MCQ & points system

Revision ID: 99e8d4cee9b8
Revises: 7f95d54fb4c7
Create Date: 2023-08-19 16:40:06.825539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e8d4cee9b8'
down_revision = '7f95d54fb4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_players', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('room_question', schema=None) as batch_op:
        batch_op.drop_column('answers')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('room_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('room_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
